<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ListMenusTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('list_menus')->truncate();
        
        \DB::table('list_menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Dashboard',
                'icon' => 'ri-apps-line',
                'route' => '/dashboard',
                'path' => 'Modules/Laboratory/Dashboard',
                'group' => 'Menu',
                'module' => 'Laboratory',
                'order' => 1,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Customers',
                'icon' => 'ri-team-fill',
                'route' => '/customers',
                'path' => 'Modules/Laboratory/Customers',
                'group' => 'Menu',
                'module' => 'Laboratory',
                'order' => 2,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Quotations',
                'icon' => 'ri-price-tag-3-fill',
                'route' => '/quotations',
                'path' => 'Modules/Laboratory/Quotations',
                'group' => 'Menu',
                'module' => 'Laboratory',
                'order' => 3,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'TS Requests',
                'icon' => 'ri-hand-coin-fill',
                'route' => '/requests',
                'path' => 'Modules/Laboratory/Tsr',
                'group' => 'Menu',
                'module' => 'Laboratory',
                'order' => 4,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Insights',
                'icon' => 'ri-line-chart-fill',
                'route' => '',
                'path' => 'Modules/Laboratory/Insights',
                'group' => 'Menu',
                'module' => 'Laboratory',
                'order' => 5,
                'has_child' => 1,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Customers',
                'icon' => NULL,
                'route' => '/insights/customers',
                'path' => '/insights/customers',
                'group' => 'Insights',
                'module' => 'Laboratory',
                'order' => 1,
                'has_child' => 0,
                'is_mother' => 0,
                'is_active' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Laboratories',
                'icon' => '',
                'route' => '/insights/laboratories',
                'path' => '/insights/laboratories',
                'group' => 'Insights',
                'module' => 'Laboratory',
                'order' => 2,
                'has_child' => 0,
                'is_mother' => 0,
                'is_active' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Reports',
                'icon' => 'ri-file-text-fill',
                'route' => '',
                'path' => 'Modules/Laboratory/Reports',
                'group' => 'Menu',
                'module' => 'Laboratory',
                'order' => 7,
                'has_child' => 1,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Test Reports',
                'icon' => '',
                'route' => '/reports/testreports',
                'path' => '/reports/testreports',
                'group' => 'Reports',
                'module' => 'Laboratory',
                'order' => 1,
                'has_child' => 0,
                'is_mother' => 0,
                'is_active' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Sample Register',
                'icon' => '',
                'route' => '/reports/samples',
                'path' => '/reports/samples',
                'group' => 'Reports',
                'module' => 'Laboratory',
                'order' => 2,
                'has_child' => 0,
                'is_mother' => 0,
                'is_active' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Dashboard',
                'icon' => 'ri-apps-line',
                'route' => '/inventory',
                'path' => 'Modules/Inventory/Dashboard',
                'group' => 'Menu',
                'module' => 'Inventory',
                'order' => 1,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Items',
                'icon' => 'ri-list-check-2',
                'route' => '/inventory/items',
                'path' => 'Modules/Inventory/Items',
                'group' => 'Menu',
                'module' => 'Inventory',
                'order' => 2,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Equipments',
                'icon' => 'ri-scales-2-fill',
                'route' => '/inventory/equipments',
                'path' => 'Modules/Inventory/Equipments',
                'group' => 'Menu',
                'module' => 'Inventory',
                'order' => 3,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Suppliers',
                'icon' => 'ri-group-2-fill',
                'route' => '/inventory/suppliers',
                'path' => 'Modules/Inventory/Suppliers',
                'group' => 'Menu',
                'module' => 'Inventory',
                'order' => 4,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Dashboard',
                'icon' => 'ri-apps-line',
                'route' => '/executive',
                'path' => 'Modules/Executive/Dashboard',
                'group' => 'Menu',
                'module' => 'Executive',
                'order' => 1,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'User Management',
                'icon' => 'ri-team-fill ',
                'route' => '/executive/users',
                'path' => 'Modules/Executive/Users',
                'group' => 'Menu',
                'module' => 'Executive',
                'order' => 2,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Role Management',
                'icon' => 'ri-shield-check-line',
                'route' => '/executive/roles',
                'path' => 'Modules/Executive/Roles',
                'group' => 'Menu',
                'module' => 'Executive',
                'order' => 3,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Menu Management',
                'icon' => 'ri-list-check',
                'route' => '/executive/menus',
                'path' => 'Modules/Executive/Menus',
                'group' => 'Menu',
                'module' => 'Executive',
                'order' => 4,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Authentication Logs',
                'icon' => 'ri-time-fill',
                'route' => '/executive/authentications',
                'path' => 'Modules/Executive/Authentications',
                'group' => 'Menu',
                'module' => 'Executive',
                'order' => 5,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Activity Logs',
                'icon' => 'ri-history-line',
                'route' => '/executive/activities',
                'path' => 'Modules/Executive/Activities',
                'group' => 'Menu',
                'module' => 'Executive',
                'order' => 6,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Backup and Restore',
                'icon' => 'ri-server-line ',
                'route' => '/executive/backups',
                'path' => 'Modules/Executive/Backups',
                'group' => 'Menu',
                'module' => 'Executive',
                'order' => 7,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Dashboard',
                'icon' => 'ri-apps-line',
                'route' => '/',
                'path' => 'Modules/Finance/Dashboard',
                'group' => 'Menu',
                'module' => 'Finance',
                'order' => 1,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Order of Payment',
                'icon' => 'ri-hand-coin-fill',
                'route' => '/finance/ops',
                'path' => 'Modules/Finance/Orders',
                'group' => 'Menu',
                'module' => 'Finance',
                'order' => 3,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Deposits',
                'icon' => 'ri-bank-card-fill',
                'route' => '/finance/deposits',
                'path' => 'Modules/Finance/Deposits',
                'group' => 'Menu',
                'module' => 'Finance',
                'order' => 4,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Collection Type',
                'icon' => 'ri-list-check',
                'route' => '/finance/collections',
                'path' => 'Modules/Finance/Collections',
                'group' => 'Menu',
                'module' => 'Finance',
                'order' => 5,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'OR Series',
                'icon' => 'ri-coupon-line',
                'route' => '/finance/orseries',
                'path' => 'Modules/Finance/Orseries',
                'group' => 'Menu',
                'module' => 'Finance',
                'order' => 6,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Names',
                'icon' => 'ri-account-circle-fill',
                'route' => '/finance/names',
                'path' => 'Modules/Finance/Names',
                'group' => 'Menu',
                'module' => 'Finance',
                'order' => 7,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Reports',
                'icon' => 'ri-line-chart-fill',
                'route' => '/finance/reports',
                'path' => 'Modules/Finance/Reports',
                'group' => 'Menu',
                'module' => 'Finance',
                'order' => 8,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Receipts',
                'icon' => 'ri-price-tag-2-fill',
                'route' => '/finance/receipts',
                'path' => 'Modules/Finance/Receipts',
                'group' => 'Menu',
                'module' => 'Finance',
                'order' => 2,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Targets',
                'icon' => 'ri-bar-chart-2-fill',
                'route' => '',
                'path' => 'Modules/Laboratory/Targets',
                'group' => 'Menu',
                'module' => 'Laboratory',
                'order' => 6,
                'has_child' => 1,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Dashboard',
                'icon' => '',
                'route' => '/targets',
                'path' => '/targets',
                'group' => 'Targets',
                'module' => 'Laboratory',
                'order' => 2,
                'has_child' => 0,
                'is_mother' => 0,
                'is_active' => 1,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Referral',
                'icon' => '',
                'route' => '/targets/referral',
                'path' => '/targets/referral',
                'group' => 'Targets',
                'module' => 'Laboratory',
                'order' => 3,
                'has_child' => 0,
                'is_mother' => 0,
                'is_active' => 1,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'PSTO',
                'icon' => '',
                'route' => '/targets/psto',
                'path' => '/targets/psto',
                'group' => 'Targets',
                'module' => 'Laboratory',
                'order' => 4,
                'has_child' => 0,
                'is_mother' => 0,
                'is_active' => 1,
            ),
        ));

        
    }
}